import React from "react";
import NavBar from "@/app/navbar";
import RegionInfo from "../regionComp";
export default function LandOfMour(){

    const linkNames = ["Characters", "Regions", "Background"];
    const sources = ["../characters", "../regions", ""];
    const imgArr = [" ", " "," "," "," "," ",];
    return (
        <>
            
            
            <div className="body">
                <NavBar linkNames={linkNames} sources={sources} />
                <RegionInfo name={"Land of Mour"} images = {imgArr}
                    background={"Welcome to the Land of Mour, a place of many ancient monsters called Horrors. You will see that these Horrors feast off the emotions of humans, making them extremely strong, and hard to combat against. Surviving against these creatures is extremely difficult to do, and rarely does any person make it out alive after encountering one. Besides the Horrors, The Land of Mour is home to many large forests, mountains, and lakes. Out of the 4 main regions, it is the largest and most populated, containing 5 major cities and home to about 2 million people."}
                    history={"The Land of Mour was the first piece of land that was cultivated by humans in the “early age”. Once civilization became more abundant, a single family overtook control of the entire region, reining in their name. They ruled the land, using its natural resources to expand its power. However, during a search campaign for resources, the kingdom's forces stumbled into the wrong part of the forest, uncovering the hidden horrors within. The monsters inside that had been dormant for hundreds of years once again became active and started to terrorize the humans of the kingdom. These monsters, later named Horrors, struck fear into the people and as time progressed, the people of the kingdom started to form their own ideals on their situation. This started to cause unrest amongst the people, in which multiple organizations and groups started to form, and they all started to try and increase their power and influence. This caused a civil war from within the kingdom, leading to its overall downfall. After the downfall of the kingdom, these sub groups started to go off on their own, claiming territory, but never going into the “forbidden territory of the Horrors”. This leads us to the Land of Mour today, a beautiful place, plagued with the fear of the Horrors."}
                    geography={"The Land of Mour is in an abundance of forests, full of different plants, animals, and monsters. However, there is one forest that stands out amongst the rest… Some call it a place of death, misunderstanding, others call it Hell. It is the Forest of Horrors, the largest forest in the Land of Mour, home to the terrifying monsters, the Horrors. The forest covers about 70% of the Land of Mour, within which lies only one town. People call these people insane, brave, or foolish, however these people have learned how to live with the Horrors. They are seldom seen. They are known to have a strange way of dress and speech, that even if one was seen, most would rather walk away and ignore that they even saw them. The Land is also surrounded with great mountains stretching from border to border. Within these mountains lie civilizations that were sick of the green of the forests and instead wanted the freshness of the air. However, these mountains aren’t freed from the Horrors below either, they too have their fair share of creatures. Some of the tallest peak of these ranges is said to be home to most of these creatures, as those who hike through this peak, or merely pass it, say that they can hear the screeching equivalent to nails on a chalkboard."}
                    exploration={"When entering the Land of Mour, it is best to visit the most popular city. The Land of Mour is surrounded by mountains, while the inside is full of forests. Entering through the north is best, as the most abundant city lies right there, and not much forest travel is required. Most of the political unrest lies in the east and west. The forest of Horrors lies in the south. Refrains from going even remotely near the forest of Horrors, as monsters sometimes like to travel on the outskirts. For the most part, most monsters live in the Forest of Horrors, however it’s not uncommon to see some monsters roaming around in neighboring forests. Make sure to carry a weapon, and always be aware of your surroundings. There are numerous roads connecting each town to each other, however there is one main road governed by the 3 biggest kingdoms in the North, East, and Western forest areas. It is recommended to take it as it’s the safest way for travel"}
                    />
            </div>
        </>
    );
}